"""add summary fields

Revision ID: 5d472d753c32
Revises: be8b6d78a24a
Create Date: 2026-01-05 22:57:02.088296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d472d753c32'
down_revision: Union[str, Sequence[str], None] = 'be8b6d78a24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listen_records', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('listen_records', sa.Column('summary_status', sa.String(length=16), server_default='PENDING', nullable=False))
    op.add_column('listen_records', sa.Column('summary_error_message', sa.String(length=512), nullable=True))
    op.create_index('idx_summary_status', 'listen_records', ['summary_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_summary_status', table_name='listen_records')
    op.drop_column('listen_records', 'summary_error_message')
    op.drop_column('listen_records', 'summary_status')
    op.drop_column('listen_records', 'summary')
    # ### end Alembic commands ###
