"""add users and elder_child_bindings

Revision ID: a26c48ae014b
Revises: 5d472d753c32
Create Date: 2026-01-05 23:11:10.500795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26c48ae014b'
down_revision: Union[str, Sequence[str], None] = '5d472d753c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('wx_openid', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wx_openid')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('elder_child_bindings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.BigInteger(), nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elder_id', 'child_id', name='uq_elder_child')
    )
    op.create_index('idx_binding_child', 'elder_child_bindings', ['child_id'], unique=False)
    op.create_index('idx_binding_elder', 'elder_child_bindings', ['elder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_binding_elder', table_name='elder_child_bindings')
    op.drop_index('idx_binding_child', table_name='elder_child_bindings')
    op.drop_table('elder_child_bindings')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
