"""init listen_records

Revision ID: be8b6d78a24a
Revises: 
Create Date: 2026-01-05 22:14:21.571423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8b6d78a24a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listen_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.BigInteger(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_elder_time', 'listen_records', ['elder_id', 'created_at'], unique=False)
    op.create_index('idx_status', 'listen_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status', table_name='listen_records')
    op.drop_index('idx_elder_time', table_name='listen_records')
    op.drop_table('listen_records')
    # ### end Alembic commands ###
